services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml
    environment:
      SWAGGER_JSON: /tmp/openapi.yaml
